#!/usr/bin/env bash
# redirection
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.github.com permanent;" /etc/nginx/sites-available/default
service nginx start
