#!/usr/bin/env bash
# Install Nginx
apt-get -y update
apt-get -y install nginx

# Create index.html
echo "Hello World!" | /var/www/html/index.html

# Add redirection rule to Nginx configuration
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.github.com permanent;" /etc/nginx/sites-available/default

# Add custom 404 page configuration
sed -i "/redirect_me/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" | /var/www/html/custom_404.html

# Restart Nginx service
sudo service nginx restart
