#!/usr/bin/env bash
# Bash script that configures a server to be running, and listening on port 80 of all the server’s active IPv4 IPs

sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
